--¼±»ý´Ô
CREATE TABLE TEACHER(
TEACHER_NUM NUMBER,
TEACHER_PWD VARCHAR2(50),
TEACHER_NAME VARCHAR2(30),
GRADE NUMBER,
CLASSES NUMBER,
CONSTRAINT TEACHER_PK PRIMARY KEY(TEACHER_NUM)
);

Insert into  TEACHER (TEACHER_NUM,TEACHER_PWD,TEACHER_NAME,GRADE,CLASSES) values (1,'1234','±èÃ¶Èñ',3,2);
Insert into  TEACHER (TEACHER_NUM,TEACHER_PWD,TEACHER_NAME,GRADE,CLASSES) values (2,'1234','Á¤´ÙÀÎ',2,1);
Insert into  TEACHER (TEACHER_NUM,TEACHER_PWD,TEACHER_NAME,GRADE,CLASSES) values (3,'1234','ÀåÈñ¹Î',1,2);
Insert into  TEACHER (TEACHER_NUM,TEACHER_PWD,TEACHER_NAME,GRADE,CLASSES) values (4,'1234','Àü¾ÆÀÎ',2,1);
Insert into  TEACHER (TEACHER_NUM,TEACHER_PWD,TEACHER_NAME,GRADE,CLASSES) values (5,'1234','±èÇý½½',2,2);
Insert into  TEACHER (TEACHER_NUM,TEACHER_PWD,TEACHER_NAME,GRADE,CLASSES) values (6,'1234','½Å¾ÆÀÎ',3,1);

SELECT * FROM TEACHER;

CREATE SEQUENCE TEACHER_NUM_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;
--ÇÐ»ý Å×ÀÌºí
CREATE TABLE STUDENT(
STUDENT_NUM NUMBER,
STUDENT_PWD VARCHAR2(50),
TEACHER_NUM NUMBER,
STUDENT_NAME VARCHAR2(30),
CONSTRAINT STUDENT_NUM_PK PRIMARY KEY(STUDENT_NUM),
CONSTRAINT TEACHAR_NUM_FK FOREIGN KEY(TEACHER_NUM) REFERENCES TEACHER(TEACHER_NUM)
); 

select * from student;
--ÇÐ»ý ½ÃÄö½º
CREATE SEQUENCE STUDENT_NUM_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (2,'1234',2,'±è¼º¹Î');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (3,'1234',2,'Àå´ÙÇý');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (1,'1234',2,'½ÅÇýÀÎ');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (4,'1234',3,'Á¤¾Æ¸§');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (5,'1234',3,'Á¤Çö»ó');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (6,'1234',3,'±è¹ÎÈñ ');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (7,'1234',4,'ÀåÃ¶¹Î');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (8,'1234',4,'±¸º»¼º');
Insert into  STUDENT (STUDENT_NUM,STUDENT_PWD,TEACHER_NUM,STUDENT_NAME) values (9,'1234',4,'Àü´Ù½½');




CREATE TABLE SUBJECT(
STUDENT_NUM NUMBER,
KOREAN NUMBER,
ENGLISH NUMBER,
MATH NUMBER,
SCIENCE NUMBER,
AVG NUMBER,
SUM NUMBER,
RANK NUMBER,
CONSTRAINT SUBJECT_PK PRIMARY KEY(STUDENT_NUM),
CONSTRAINT SUBJECT_FK FOREIGN KEY(STUDENT_NUM) REFERENCES STUDENT(STUDENT_NUM)
);

Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (3,20,20,20,20,20,80,1);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (1,5,5,5,5,5,20,3);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (4,20,20,20,20,20,80,3);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (5,30,30,30,30,30,120,2);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (6,100,100,100,100,100,400,1);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (2,10,10,10,10,10,40,2);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (7,42,22,12,77,38.25,153,3);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (8,100,100,100,100,100,400,1);
Insert into  SUBJECT (STUDENT_NUM,KOREAN,ENGLISH,MATH,SCIENCE,AVG,SUM,RANK) values (9,100,100,100,100,100,400,1);